### ISSUE TITLE
SpikeDislike3 v1.8 crashes

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#100]
> glandrid: Just wanted to report SpikeDislike3 isn't working.  Not for me anyway; it crashes as soon as you start playing

> GGalemb: @ProHiScore There are 2 versions on Internet Archive, and 1.8 does freeze indeed. V1.6 runs fine.

http://ouya.cweiske.de/game/com.AGameAWeek.SpikeDislike3_I15.htm

Game website: https://agameaweek.com/?Game=351

----

The crash happens when playing the first level, when jumping over the first spike.

It seems a sound sample cannot be loaded. The game hangs for ~10 seconds and then crashes.

----

```
I/[Monkey]( 1373): sfx/title_full.ogg
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/ActivityManager(  349): Displayed com.AGameAWeek.SpikeDislike3_I15/.MonkeyGame: +578ms
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
E/SoundPool( 1373): Unable to load sample: (null)
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
D/dalvikvm( 1373): JIT code cache reset in 0 ms (4096 bytes 2/0)
I/[Monkey]( 1373): -1
I/[Monkey]( 1373): dc4619eefd76423d152d1b3789814fb245dfd008
I/[Monkey]( 1373): -1
I/[Monkey]( 1373): 1:1
I/[Monkey]( 1373): sfx/world001.ogg
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
I/InputDispatcher(  349): Application is not responding: AppWindowToken{4223ab28 token=Token{42121b20 ActivityRecord{420add70 com.AGameAWeek.SpikeDislike3_I15/.MonkeyGame}}} - Window{4203bdd0 com.AGameAWeek.SpikeDislike3_I15/com.AGameAWeek.SpikeDislike3_I15.MonkeyGame paused=false}.  It has been 5006.3ms since event, 5005.9ms since wait started.  Reason: Waiting because the focused window has not finished processing the input events that were previously delivered to it.
I/WindowManager(  349): Input event dispatching timed out sending to com.AGameAWeek.SpikeDislike3_I15/com.AGameAWeek.SpikeDislike3_I15.MonkeyGame
I/Process (  349): Sending signal. PID: 1373 SIG: 3
I/dalvikvm( 1373): threadid=3: reacting to signal 3
W/SoundPool( 1373):   sample 7 not READY
I/dalvikvm( 1373): Wrote stack traces to '/data/anr/traces.txt'
I/Process (  349): Sending signal. PID: 349 SIG: 3
I/dalvikvm(  349): threadid=3: reacting to signal 3
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
I/Process (  349): Sending signal. PID: 546 SIG: 3
I/dalvikvm(  546): threadid=3: reacting to signal 3
I/dalvikvm(  349): Wrote stack traces to '/data/anr/traces.txt'
I/Process (  349): Sending signal. PID: 447 SIG: 3
I/dalvikvm(  447): threadid=3: reacting to signal 3
I/dalvikvm(  447): Wrote stack traces to '/data/anr/traces.txt'
I/dalvikvm(  546): Wrote stack traces to '/data/anr/traces.txt'
W/SoundPool( 1373):   sample 7 not READY
I/dalvikvm(  349): Jit: resizing JitTable from 4096 to 8192
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
D/AndroidRuntime( 1373): Shutting down VM
W/dalvikvm( 1373): threadid=1: thread exiting with uncaught exception (group=0x40fb8300)
E/AndroidRuntime( 1373): FATAL EXCEPTION: main
E/AndroidRuntime( 1373): java.lang.Error: PlaySample failed to play sound
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.gxtkAudio.PlaySample(MonkeyGame.java:2911)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.bb_audio.g_PlaySound(MonkeyGame.java:11512)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_MyApp.p_PlaySFX(MonkeyGame.java:4793)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_MyApp.p_Game_Ball(MonkeyGame.java:7867)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_MyApp.p_OnUpdate(MonkeyGame.java:10175)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_GameDelegate.UpdateGame(MonkeyGame.java:10495)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.BBGame.UpdateGame(MonkeyGame.java:606)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.BBAndroidGame.UpdateGame(MonkeyGame.java:1420)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.BBAndroidGame$GameTimer.run(MonkeyGame.java:888)
E/AndroidRuntime( 1373): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 1373): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1373): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1373): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 1373): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1373): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1373): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 1373): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1373): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 1373): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  349):   Force finishing activity com.AGameAWeek.SpikeDislike3_I15/.MonkeyGame
I/dalvikvm-heap(  349): Grow heap (frag case) to 20.557MB for 380496-byte allocation
I/Process ( 1373): Sending signal. PID: 1373 SIG: 9
V/DropBoxReceiver(  571): Starting service for tag: data_app_crash, time: 1603690743721
D/CrashReportService(  571): Writing crash report to: /data/user/0/tv.ouya/cache/.reports/1603690743721
I/WindowState(  349): WIN DEATH: Window{4203bdd0 com.AGameAWeek.SpikeDislike3_I15/com.AGameAWeek.SpikeDislike3_I15.MonkeyGame paused=true}
W/AudioFlinger(  110): session id 21 not found for pid 110
I/ActivityManager(  349): Process com.AGameAWeek.SpikeDislike3_I15 (pid 1373) has died.
```

**Comment by cweiske** [comment]
> GGalemb: @ProHiScore There are 2 versions on Internet Archive, and 1.8 does freeze indeed. V1.6 runs fine.

**Comment by cweiske** [comment]
```
I/[Monkey]( 1373): sfx/title_full.ogg
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/ActivityManager(  349): Displayed com.AGameAWeek.SpikeDislike3_I15/.MonkeyGame: +578ms
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
E/SoundPool( 1373): Unable to load sample: (null)
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
D/dalvikvm( 1373): JIT code cache reset in 0 ms (4096 bytes 2/0)
I/[Monkey]( 1373): -1
I/[Monkey]( 1373): dc4619eefd76423d152d1b3789814fb245dfd008
I/[Monkey]( 1373): -1
I/[Monkey]( 1373): 1:1
I/[Monkey]( 1373): sfx/world001.ogg
I/NuCachedSource2(  110): ERROR_END_OF_STREAM
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
I/InputDispatcher(  349): Application is not responding: AppWindowToken{4223ab28 token=Token{42121b20 ActivityRecord{420add70 com.AGameAWeek.SpikeDislike3_I15/.MonkeyGame}}} - Window{4203bdd0 com.AGameAWeek.SpikeDislike3_I15/com.AGameAWeek.SpikeDislike3_I15.MonkeyGame paused=false}.  It has been 5006.3ms since event, 5005.9ms since wait started.  Reason: Waiting because the focused window has not finished processing the input events that were previously delivered to it.
I/WindowManager(  349): Input event dispatching timed out sending to com.AGameAWeek.SpikeDislike3_I15/com.AGameAWeek.SpikeDislike3_I15.MonkeyGame
I/Process (  349): Sending signal. PID: 1373 SIG: 3
I/dalvikvm( 1373): threadid=3: reacting to signal 3
W/SoundPool( 1373):   sample 7 not READY
I/dalvikvm( 1373): Wrote stack traces to '/data/anr/traces.txt'
I/Process (  349): Sending signal. PID: 349 SIG: 3
I/dalvikvm(  349): threadid=3: reacting to signal 3
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
I/Process (  349): Sending signal. PID: 546 SIG: 3
I/dalvikvm(  546): threadid=3: reacting to signal 3
I/dalvikvm(  349): Wrote stack traces to '/data/anr/traces.txt'
I/Process (  349): Sending signal. PID: 447 SIG: 3
I/dalvikvm(  447): threadid=3: reacting to signal 3
I/dalvikvm(  447): Wrote stack traces to '/data/anr/traces.txt'
I/dalvikvm(  546): Wrote stack traces to '/data/anr/traces.txt'
W/SoundPool( 1373):   sample 7 not READY
I/dalvikvm(  349): Jit: resizing JitTable from 4096 to 8192
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
W/SoundPool( 1373):   sample 7 not READY
D/AndroidRuntime( 1373): Shutting down VM
W/dalvikvm( 1373): threadid=1: thread exiting with uncaught exception (group=0x40fb8300)
E/AndroidRuntime( 1373): FATAL EXCEPTION: main
E/AndroidRuntime( 1373): java.lang.Error: PlaySample failed to play sound
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.gxtkAudio.PlaySample(MonkeyGame.java:2911)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.bb_audio.g_PlaySound(MonkeyGame.java:11512)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_MyApp.p_PlaySFX(MonkeyGame.java:4793)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_MyApp.p_Game_Ball(MonkeyGame.java:7867)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_MyApp.p_OnUpdate(MonkeyGame.java:10175)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.c_GameDelegate.UpdateGame(MonkeyGame.java:10495)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.BBGame.UpdateGame(MonkeyGame.java:606)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.BBAndroidGame.UpdateGame(MonkeyGame.java:1420)
E/AndroidRuntime( 1373): 	at com.AGameAWeek.SpikeDislike3_I15.BBAndroidGame$GameTimer.run(MonkeyGame.java:888)
E/AndroidRuntime( 1373): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 1373): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1373): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1373): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 1373): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1373): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1373): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 1373): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1373): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 1373): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  349):   Force finishing activity com.AGameAWeek.SpikeDislike3_I15/.MonkeyGame
I/dalvikvm-heap(  349): Grow heap (frag case) to 20.557MB for 380496-byte allocation
I/Process ( 1373): Sending signal. PID: 1373 SIG: 9
V/DropBoxReceiver(  571): Starting service for tag: data_app_crash, time: 1603690743721
D/CrashReportService(  571): Writing crash report to: /data/user/0/tv.ouya/cache/.reports/1603690743721
I/WindowState(  349): WIN DEATH: Window{4203bdd0 com.AGameAWeek.SpikeDislike3_I15/com.AGameAWeek.SpikeDislike3_I15.MonkeyGame paused=true}
W/AudioFlinger(  110): session id 21 not found for pid 110
I/ActivityManager(  349): Process com.AGameAWeek.SpikeDislike3_I15 (pid 1373) has died.
```

**Comment by cweiske** [comment]
We're making only v1.6 available in the store.
