### ISSUE TITLE
Elliot Quest: Crash on startup

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#32]
On startup, elliot quest crashes.
It tries to decrypt some configuration data using `cipher.doFinal()` which fails because of ouya-plain-purchases. (`com.ideateca.core.util.decipher`)

```
D/IDTKLog ( 2246): IDTK_LOG_DEBUG: [IDTK] Invoked in string&) line 53: Reflective class 'ludei::framework::Service' registered.
D/dalvikvm( 2246): Added shared lib /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so 0x4235a9d0
D/IDTKLog ( 2246): IDTK_LOG_DEBUG: [IDTK] Invoked in JNI_OnLoad line 52: cocoon gets the JavaVM!!!
W/System.err( 2246): net.sf.plist.io.PropertyListException: The property list is not a valid XML document.
W/System.err( 2246): 	at net.sf.plist.io.domxml.DOMXMLParser.<init>(DOMXMLParser.java:112)
W/System.err( 2246): 	at net.sf.plist.io.domxml.DOMXMLParser.<init>(DOMXMLParser.java:89)
W/System.err( 2246): 	at net.sf.plist.io.PropertyListParser.parse(PropertyListParser.java:104)
W/System.err( 2246): 	at com.ideateca.core.util.PListUtils.fromPListToJSON(PListUtils.java:59)
W/System.err( 2246): 	at com.ideateca.core.framework.IDTKApplication.onCreate(IDTKApplication.java:34)
W/System.err( 2246): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
W/System.err( 2246): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
W/System.err( 2246): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 2246): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:640)
W/System.err( 2246): 	at android.app.ActivityThread.handleBindApplication(Native Method)
W/System.err( 2246): 	at android.app.ActivityThread.access$1300(ActivityThread.java:130)
W/System.err( 2246): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
W/System.err( 2246): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 2246): 	at android.os.Looper.loop(Looper.java:137)
W/System.err( 2246): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
W/System.err( 2246): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2246): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 2246): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
W/System.err( 2246): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
W/System.err( 2246): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
W/System.err( 2246): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err( 2246): Caused by: org.xml.sax.SAXParseException: Unexpected token (position:TEXT ZI���wfD���芉���9...@1:66 in java.io.InputStreamReader@423a9448) 
W/System.err( 2246): 	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
W/System.err( 2246): 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
W/System.err( 2246): 	at net.sf.plist.io.domxml.DOMXMLParser.<init>(DOMXMLParser.java:110)
W/System.err( 2246): 	... 20 more
W/System.err( 2246): org.json.JSONException: No value for ApplicationContext
W/System.err( 2246): 	at org.json.JSONObject.get(JSONObject.java:354)
W/System.err( 2246): 	at com.ideateca.core.framework.IDTKApplication.onCreate(IDTKApplication.java:37)
W/System.err( 2246): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
W/System.err( 2246): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
W/System.err( 2246): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 2246): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:640)
W/System.err( 2246): 	at android.app.ActivityThread.handleBindApplication(Native Method)
W/System.err( 2246): 	at android.app.ActivityThread.access$1300(ActivityThread.java:130)
W/System.err( 2246): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
W/System.err( 2246): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 2246): 	at android.os.Looper.loop(Looper.java:137)
W/System.err( 2246): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
W/System.err( 2246): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2246): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 2246): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
W/System.err( 2246): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
W/System.err( 2246): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
W/System.err( 2246): 	at dalvik.system.NativeStart.main(Native Method)
D/OpenUDID( 2246): 1 services matches OpenUDID
D/OpenUDID( 2246): Trying service Elliot Quest
D/OpenUDID( 2246): Successfully connected to service: com.ansimuz.ElliotQuest/org.OpenUDID.OpenUDID_service
I/WindowManager(  379): Switching to real app window: Window{426d8f58 com.ansimuz.ElliotQuest/com.ansimuz.ElliotQuest.Elliot_QuestActivity paused=false}
D/libEGL  ( 2246): loaded /system/lib/egl/libEGL_tegra.so
E/        ( 2246): file /data/data/com.nvidia.NvCPLSvc/files/driverlist.txt: not found!
I/        ( 2246): Attempting to load EGL implementation /system/lib//egl/libEGL_tegra_impl
I/        ( 2246): Loaded EGL implementation /system/lib//egl/libEGL_tegra_impl
D/libEGL  ( 2246): loaded /system/lib/egl/libGLESv1_CM_tegra.so
D/libEGL  ( 2246): loaded /system/lib/egl/libGLESv2_tegra.so
I/        ( 2246): Loading GLESv2 implementation /system/lib//egl/libGLESv2_tegra_impl
D/OpenGLRenderer( 2246): Enabling debug mode 0
D/OpenUDID( 2246): Generating openUDID
D/OpenUDID( 2246): OpenUDID: e49ddd0f18400bde
I/System.out( 2246): SET LOG LEVEL = 1
I/ActivityManager(  379): Displayed com.ansimuz.ElliotQuest/.Elliot_QuestActivity: +580ms
E/IDTKLog ( 2246): IDTK_LOG_ERROR: [IDTK] Invoked in void ludei::framework::AndroidApplication::launched line 245: ResourceManagerImpl::load = unable to load file [TinyXML says: Error document empty.]
F/libc    ( 2246): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 2262 (Thread-131)
I/Choreographer(  590): Skipped 42 frames!  The application may be doing too much work on its main thread.
I/DEBUG   (  108): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  108): Build fingerprint: 'OUYA/ouya_1_1/ouya_1_1:4.1.2/JZO54L-OUYA/1427:user/test-keys'
I/DEBUG   (  108): pid: 2246, tid: 2262, name: Thread-131  >>> com.ansimuz.ElliotQuest <<<
I/DEBUG   (  108): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
I/DEBUG   (  108):     r0 00000027  r1 deadbaad  r2 4013daec  r3 00000000
I/DEBUG   (  108):     r4 00000000  r5 68c1bacc  r6 689ef6a0  r7 66998e78
I/DEBUG   (  108):     r8 0000004e  r9 fffffd6c  sl 68846d30  fp 68c1bb98
I/DEBUG   (  108):     ip 68a90dec  sp 68c1bac8  lr 4010fe41  pc 4010c4e2  cpsr 60000030
I/DEBUG   (  108):     d0  0000100000000000  d1  0000100045800000
I/DEBUG   (  108):     d2  3e01030a45800000  d3  b8025efb3c0102b3
I/DEBUG   (  108):     d4  b8025ebeaf7264cc  d5  bb360b4fbcc00000
I/DEBUG   (  108):     d6  3f8000003f800000  d7  0000000000000000
I/DEBUG   (  108):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  108):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  108):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  108):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  108):     d16 0000000000000001  d17 0000000000000000
I/DEBUG   (  108):     d18 0000000000000000  d19 00bc800000b98000
I/DEBUG   (  108):     d20 00b6802e00b3802d  d21 00bc802f00b9802f
I/DEBUG   (  108):     d22 0707070703030303  d23 0000002f0000002e
I/DEBUG   (  108):     d24 0000000000000000  d25 0000000000000000
I/DEBUG   (  108):     d26 0000002f0000002f  d27 0000002f0000002f
I/DEBUG   (  108):     d28 0001000000010000  d29 0001000000010000
I/DEBUG   (  108):     d30 0003000000030000  d31 0003000000030000
I/DEBUG   (  108):     scr 80000011
I/DEBUG   (  108): 
I/DEBUG   (  108): backtrace:
I/DEBUG   (  108):     #00  pc 000184e2  /system/lib/libc.so
I/DEBUG   (  108):     #01  pc 0000dc24  /system/lib/libc.so (abort+4)
I/DEBUG   (  108):     #02  pc 00742c5c  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so (__gnu_cxx::__verbose_terminate_handler()+344)
I/DEBUG   (  108): 
I/DEBUG   (  108): stack:
I/DEBUG   (  108):          68c1ba88  401386f8  /system/lib/libc.so
I/DEBUG   (  108):          68c1ba8c  68c1bacc  
I/DEBUG   (  108):          68c1ba90  401386f8  /system/lib/libc.so
I/DEBUG   (  108):          68c1ba94  0000000e  
I/DEBUG   (  108):          68c1ba98  401386f8  /system/lib/libc.so
I/DEBUG   (  108):          68c1ba9c  68c1badc  
I/DEBUG   (  108):          68c1baa0  40138754  /system/lib/libc.so
I/DEBUG   (  108):          68c1baa4  4013dcf0  
I/DEBUG   (  108):          68c1baa8  00000000  
I/DEBUG   (  108):          68c1baac  4010fe41  /system/lib/libc.so (_fwalk+32)
I/DEBUG   (  108):          68c1bab0  00000001  
I/DEBUG   (  108):          68c1bab4  68c1bacc  
I/DEBUG   (  108):          68c1bab8  689ef6a0  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so
I/DEBUG   (  108):          68c1babc  66998e78  
I/DEBUG   (  108):          68c1bac0  df0027ad  
I/DEBUG   (  108):          68c1bac4  00000000  
I/DEBUG   (  108):     #00  68c1bac8  0000000a  
I/DEBUG   (  108):          68c1bacc  fffffbdf  
I/DEBUG   (  108):          68c1bad0  0000000a  
I/DEBUG   (  108):          68c1bad4  4011315b  /system/lib/libc.so (__swbuf+102)
I/DEBUG   (  108):          68c1bad8  00000001  
I/DEBUG   (  108):          68c1badc  401386f8  /system/lib/libc.so
I/DEBUG   (  108):          68c1bae0  401386f8  /system/lib/libc.so
I/DEBUG   (  108):          68c1bae4  40138650  /system/lib/libc.so
I/DEBUG   (  108):          68c1bae8  00000001  
I/DEBUG   (  108):          68c1baec  40101c28  /system/lib/libc.so (__pthread_clone)
I/DEBUG   (  108):     #01  68c1baf0  4013878c  /system/lib/libc.so
I/DEBUG   (  108):          68c1baf4  6888ac60  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so (__gnu_cxx::__verbose_terminate_handler()+348)
I/DEBUG   (  108):     #02  68c1baf8  669e7858  
I/DEBUG   (  108):          68c1bafc  00000000  
I/DEBUG   (  108):          68c1bb00  00000055  
I/DEBUG   (  108):          68c1bb04  669e7858  
I/DEBUG   (  108):          68c1bb08  00000000  
I/DEBUG   (  108):          68c1bb0c  00000055  
I/DEBUG   (  108):          68c1bb10  00000047  
I/DEBUG   (  108):          68c1bb14  68846d04  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so (__cxxabiv1::__terminate(void (*)())+8)
I/DEBUG   (  108):          68c1bb18  68a94e14  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so
I/DEBUG   (  108):          68c1bb1c  68846d4c  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so (std::terminate()+28)
I/DEBUG   (  108):          68c1bb20  66fcf5e0  
I/DEBUG   (  108):          68c1bb24  68848b24  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so (__cxa_throw+160)
I/DEBUG   (  108):          68c1bb28  68a90984  /data/data/com.ansimuz.ElliotQuest/lib/libCocoonJSLib.so
I/DEBUG   (  108):          68c1bb2c  68c1bc18  
I/DEBUG   (  108):          68c1bb30  68c1bc10  
I/DEBUG   (  108):          68c1bb34  68c1bbd0  
```

**Comment by cweiske** [comment]
Fixed with ouya-plain-purchases v1.1.0
