### ISSUE TITLE
Towerfall: org.json.JSONException: No value for priceInCents

### ISSUE THREAD

**Issue by cweiske** [ouya-saviors/ouya-game-data#74]
When starting Towerfall, it crashes with:
```
D/Ouya.CSharp.PurchaseUtils( 5414): CreateReceiptsFromResponse: started
D/Ouya.CSharp.PurchaseUtils( 5414): CreateReceiptsFromResponse: decrypting response
E/Ouya.CSharp.PurchaseUtils( 5414): Unable to create purchase receipts
E/Ouya.CSharp.PurchaseUtils( 5414): org.json.JSONException: No value for priceInCents
E/Ouya.CSharp.PurchaseUtils( 5414): 	at org.json.JSONObject.get(JSONObject.java:354)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at org.json.JSONObject.getInt(JSONObject.java:443)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at tv.ouya.console.api.OuyaEncryptionHelper.createReceipt(OuyaEncryptionHelper.java:219)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at tv.ouya.console.api.OuyaEncryptionHelper.parseJSONReceiptResponse(OuyaEncryptionHelper.java:140)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at tv.ouya.console.api.OuyaEncryptionHelper.decryptReceiptResponse(OuyaEncryptionHelper.java:57)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at ouya.csharp.PurchaseUtils.CreateReceiptsFromResponse(PurchaseUtils.java:158)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at ouya.console.api.ReceiptsListener.n_onSuccess(Native Method)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at ouya.console.api.ReceiptsListener.onSuccess(ReceiptsListener.java:47)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at tv.ouya.console.internal.ListenerBinderHelper$1.run(ListenerBinderHelper.java:20)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at android.os.Handler.handleCallback(Handler.java:615)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at android.os.Looper.loop(Looper.java:137)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
E/Ouya.CSharp.PurchaseUtils( 5414): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by cweiske** [comment]
Cause: The server did not send proper purchase requests. Use ouya.cweiske.de, which does.
