### ISSUE TITLE
All the Sonic games on OUYA Discover crash with OUYA plain purchases module enabled

### ISSUE THREAD

**Issue by StiraGHB** [ouya-saviors/ouya-game-data#94]
Hello,

Whenever I have the OUYA plain purchases module enabled, Sonic CD, Sonic 4 Episode I and Sonic 4 Episode II crash when opened. When the module is disabled, the games work, but only as trial versions. What could I do to possibly fix this?

Thank you,
Stira

**Comment by cweiske** [comment]
Could you get a log from "adb logcat" with the crash/exception message?

**Comment by StiraGHB** [comment]
Here are the results for Sonic CD and Sonic 4 Episode 1.
[sonicouya.txt](https://github.com/ouya-saviors/ouya-game-data/files/5059651/sonicouya.txt)

**Comment by cweiske** [comment]
Relevant error message:
```
E/AndroidRuntime( 7653): java.lang.RuntimeException: org.json.JSONException: No value for priceInCents
E/AndroidRuntime( 7653): 	at com.sega.soniccd.SonicCDActivity$1.onSuccess(SonicCDActivity.java:123)
E/AndroidRuntime( 7653): 	at com.sega.soniccd.SonicCDActivity$1.onSuccess(SonicCDActivity.java:1)
E/AndroidRuntime( 7653): 	at tv.ouya.console.internal.ListenerBinderHelper$1.run(ListenerBinderHelper.java:20)
E/AndroidRuntime( 7653): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 7653): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 7653): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 7653): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 7653): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7653): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 7653): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 7653): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 7653): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
E/AndroidRuntime( 7653): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 7653): Caused by: org.json.JSONException: No value for priceInCents
E/AndroidRuntime( 7653): 	at org.json.JSONObject.get(JSONObject.java:354)
E/AndroidRuntime( 7653): 	at org.json.JSONObject.getInt(JSONObject.java:443)
E/AndroidRuntime( 7653): 	at tv.ouya.console.api.OuyaEncryptionHelper.createReceipt(OuyaEncryptionHelper.java:219)
E/AndroidRuntime( 7653): 	at tv.ouya.console.api.OuyaEncryptionHelper.parseJSONReceiptResponse(OuyaEncryptionHelper.java:140)
E/AndroidRuntime( 7653): 	at tv.ouya.console.api.OuyaEncryptionHelper.decryptReceiptResponse(OuyaEncryptionHelper.java:57)
E/AndroidRuntime( 7653): 	at com.sega.soniccd.SonicCDActivity$1.onSuccess(SonicCDActivity.java:106)
E/AndroidRuntime( 7653): 	... 12 more
```

Which server do you use?

**Comment by StiraGHB** [comment]
I use the server here: https://ouya.world/t/how-to-bypass-account-login-firmware-update-page/15

**Comment by cweiske** [comment]
Try http://ouya.cweiske.de
-- 
Regards/Mit freundlichen Grüßen
Christian Weiske

**Comment by StiraGHB** [comment]
I did, and it luckily works. However, the games are still in demo/trial mode.

**Comment by cweiske** [comment]
What happens when you buy them in-game?
-- 
Regards/Mit freundlichen Grüßen
Christian Weiske

**Comment by StiraGHB** [comment]
Nevermind, I got it to work. Thank you so much for the support though!

**Comment by cweiske** [comment]
@Szeraax See my comment about priceInCents - your server misses it, you need to add it.

**Comment by Szeraax** [comment]
Thanks, I'll fix that up tomorrow. Sorry.

**Comment by cweiske** [comment]
Ah, we already had that problem earlier: #74

**Comment by Szeraax** [comment]
Ah ha, now I know why I had it disabled. Your API doc lists it as an optional field. Fixed and pushed to production. Should now work on both servers.
